### ISSUE TITLE
Add safetygraphics.org domain link and github source to landing page

### ISSUE THREAD

**Issue by xni7** [SafetyGraphics/RPharma2021-Workshop#13]
@jwildfire @MayaGans , i  have pointed safetygraphics.org to the workshop landing page for easier memory

- [safetygraphics.org](http://safetygraphics.org)  or
- [safetygraphics.org/workshop](http://safetygraphics.org/workshop)

I plan to hold the domain for a couple of years ;)

**Comment by MayaGans** [comment]
Love this, thanks Xiao!! 🥳 After the workshop/when things settle down I'd be happy to brainstorm a more fleshed out website where the workshop is just one item in the navbar too!
