### ISSUE TITLE
add link to chat for use during workshop

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/RPharma2021-Workshop#16]

**Comment by jwildfire** [comment]
@xni7 @MayaGans Any recommendations for best chat to use?

**Comment by xni7** [comment]
one thought is slack - if assuming R in Pharma conference attendees are already registered with slack, would it be an option to open a channel in Slack under R in Pharma 2021 [rinpharmaconf.slack.com](http://rinpharmaconf.slack.com)? I know we also talked about [gitter](https://gitter.im/js4shiny/rstudio-conf-2020)
