### ISSUE TITLE
Add relevant links to website

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/RPharma2021-Workshop#7]

**Comment by MayaGans** [comment]
Hey @jwildfire happy to do this! Would you mind throwing the links in here so I can add what you're thinking? We can do it on our Friday call if that's easier too :)

**Comment by jwildfire** [comment]
@MayaGans I just went in and made some updates - would you mind doing a QC and seeing if you think there's anything else to put in? Thanks!
